# -*- coding: utf-8 -*-
"""student_record_management_system.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dYLEfzuhbYOZsmU8YDJKhJ3mwznTqDJi
"""

# Student Record Management System in Python
students = []


def add_student(student_id, name, age, grade):
    for s in students:
        if s['id'] == student_id:
            print("Error: Student ID already exists!")
            return

    student = {
        'id': student_id,
        'name': name,
        'age': age,
        'grade': grade
    }
    students.append(student)
    print(f"Student '{name}' added successfully!")


def view_students():
    if not students:
        print("No student records found.")
        return

    print("\n--- Student Records ---")
    for s in students:
        print(f"ID: {s['id']}, Name: {s['name']}, Age: {s['age']}, Grade: {s['grade']}")
    print("------------------------\n")


def search_student(keyword):
    keyword = keyword.lower()
    results = [s for s in students if keyword in s['id'].lower() or keyword in s['name'].lower()]

    if not results:
        print("No matching student found.")
        return

    print("\n--- Search Results ---")
    for s in results:
        print(f"ID: {s['id']}, Name: {s['name']}, Age: {s['age']}, Grade: {s['grade']}")
    print("-----------------------\n")

def update_student(student_id, new_name=None, new_age=None, new_grade=None):
    for s in students:
        if s['id'] == student_id:
            if new_name:
                s['name'] = new_name
            if new_age:
                s['age'] = new_age
            if new_grade:
                s['grade'] = new_grade
            print(f"Student (ID: {student_id}) updated successfully!")
            return

    print("Error: Student ID not found.")


def delete_student(student_id):
    for s in students:
        if s['id'] == student_id:
            students.remove(s)
            print(f"Student (ID: {student_id}) deleted successfully!")
            return

    print("Error: Student ID not found.")


def main():
    while True:
        print("\n====== Student Record Management ======")
        print("1. Add Student")
        print("2. View Students")
        print("3. Search Student")
        print("4. Update Student")
        print("5. Delete Student")
        print("6. Exit")

        choice = input("Enter your choice: ")

        if choice == '1':
            sid = input("Enter ID: ")
            name = input("Enter Name: ")
            age = input("Enter Age: ")
            grade = input("Enter Grade: ")
            add_student(sid, name, age, grade)

        elif choice == '2':
            view_students()

        elif choice == '3':
            keyword = input("Enter ID or Name to search: ")
            search_student(keyword)

        elif choice == '4':
            sid = input("Enter Student ID to update: ")
            name = input("New Name (Leave empty to skip): ")
            age = input("New Age (Leave empty to skip): ")
            grade = input("New Grade (Leave empty to skip): ")
            update_student(sid, name or None, age or None, grade or None)

        elif choice == '5':
            sid = input("Enter Student ID to delete: ")
            delete_student(sid)

        elif choice == '6':
            print("Exiting program…")
            break

        else:
            print("Invalid choice. Please try again.")

if __name__ == "__main__":
    main()